# Generated by go2rpm 1.8.0
%bcond_without check

# https://github.com/zricethezav/gitleaks
%global forgeurl        https://github.com/zricethezav/gitleaks
%global goipath         github.com/zricethezav/gitleaks/v8
Version:                8.16.4

%gometa -f

%global common_description %{expand:
Scan git repos (or files) for secrets using regex and entropy}

%global golicenses      LICENSE
%global godocs          CONTRIBUTING.md README.md

Name:           gitleaks
Release:        %autorelease
Summary:        Scan git repos (or files) for secrets using regex and entropy

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

BuildRequires:  git-core
%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/bin/gitleaks %{goipath}
%{gobuilddir}/bin/%{name} completion bash > %{name}.bash
%{gobuilddir}/bin/%{name} completion fish > %{name}.fish
%{gobuilddir}/bin/%{name} completion zsh  > %{name}.zsh


%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
install -Dpm 0644 %{name}.bash %{buildroot}%{bash_completions_dir}/%{name}
install -Dpm 0644 %{name}.fish %{buildroot}%{fish_completions_dir}/%{name}.fish
install -Dpm 0644 %{name}.zsh  %{buildroot}%{zsh_completions_dir}/_%{name}


%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc CONTRIBUTING.md README.md
%{_bindir}/*
%{bash_completions_dir}/%{name}
%{fish_completions_dir}/%{name}.fish
%{zsh_completions_dir}/_%{name}


%gopkgfiles

%changelog
%autochangelog
