# Generated by go2rpm 1.7.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/google/cel-go
%global goipath         github.com/google/cel-go
Version:                0.12.4

%gometa -f

%global common_description %{expand:
The Common Expression Language (CEL) is a non-Turing complete language designed
for simplicity, speed, safety, and portability. CEL's C-like syntax looks nearly
identical to equivalent expressions in C++, Go, Java, and TypeScript.}

%global golicenses      LICENSE
%global godocs          examples CODE_OF_CONDUCT.md CONTRIBUTING.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Fast, portable, non-Turing complete expression evaluation

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

BuildRequires:  antlr4

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
# Regenerate ANTLR files
pushd parser/gen
antlr4 -Dlanguage=Go -package gen -visitor CEL.g4
popd

%install
%gopkginstall

%if %{with check}
%check
# Some tests fail due to overflows
%if 0%{?__isa_bits} == 32
rm -rfv common/types/int_test.go
%endif
# server fails but you need first to check it for undefined behavior with cel-spec
%gocheck -d server
%endif

%gopkgfiles

%changelog
%autochangelog
