# Generated by go2rpm 1.9.0
# Disable tests - require superuser for mount
%bcond_with check
%global debug_package %{nil}

# https://github.com/dennwc/btrfs
%global goipath         github.com/dennwc/btrfs
%global commit          a1f570bd01a14302c88f46fc37fc3018a60f3370

%gometa -f

%global common_description %{expand:
Btrfs library in a pure Go.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Btrfs library in a pure Go

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
