# Generated by go2rpm
%bcond_without check

# https://github.com/aws/aws-sdk-go-v2
%global goipath         github.com/aws/aws-sdk-go-v2
Version:                1.8.0

%gometa

%global common_description %{expand:
aws-sdk-go-v2 is the Developer Preview for the v2 of the AWS SDK for the Go
programming language.}

%global golicenses      LICENSE.txt NOTICE.txt
%global godocs          example CHANGELOG.md CHANGELOG_PENDING.md CODE_OF_CONDUCT.md CONTRIBUTING.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        AWS SDK for the Go programming language

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/aws/smithy-go)
BuildRequires:  golang(github.com/aws/smithy-go/document)
BuildRequires:  golang(github.com/aws/smithy-go/document/json)
BuildRequires:  golang(github.com/aws/smithy-go/encoding/httpbinding)
BuildRequires:  golang(github.com/aws/smithy-go/encoding/json)
BuildRequires:  golang(github.com/aws/smithy-go/encoding/xml)
BuildRequires:  golang(github.com/aws/smithy-go/io)
BuildRequires:  golang(github.com/aws/smithy-go/logging)
BuildRequires:  golang(github.com/aws/smithy-go/middleware)
BuildRequires:  golang(github.com/aws/smithy-go/ptr)
BuildRequires:  golang(github.com/aws/smithy-go/rand)
BuildRequires:  golang(github.com/aws/smithy-go/time)
BuildRequires:  golang(github.com/aws/smithy-go/transport/http)
BuildRequires:  golang(github.com/aws/smithy-go/waiter)
BuildRequires:  golang(github.com/jmespath/go-jmespath)
BuildRequires:  golang(github.com/olekukonko/tablewriter)
BuildRequires:  golang(github.com/pelletier/go-toml)
BuildRequires:  golang(golang.org/x/mod/modfile)
BuildRequires:  golang(golang.org/x/mod/module)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/corehandlers)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/credentials)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/request)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/session)
BuildRequires:  golang(github.com/aws/aws-sdk-go/awstesting/unit)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/dynamodb)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/lexruntimeservice)
BuildRequires:  golang(github.com/aws/smithy-go/testing)
BuildRequires:  golang(github.com/google/go-cmp/cmp)
BuildRequires:  golang(github.com/google/go-cmp/cmp/cmpopts)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
# aws/external: needs network
%gocheck -t aws/external -d aws/retry -t internal/repotools/changes -d service/internal/benchmark/dynamodb
%endif

%gopkgfiles

%changelog
%autochangelog
