# Generated by go2rpm 1
%bcond_without check

# https://github.com/coredns/corefile-migration
%global goipath         github.com/coredns/corefile-migration
Version:                1.0.11

%gometa

%global common_description %{expand:
Library and tools for migrating the CoreDNS corefile.}

%global golicenses      LICENSE
%global godocs          README.md corefile-tool/README.md

Name:           %{goname}
Release:        9%{?dist}
Summary:        Library and tools for migrating the CoreDNS corefile

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/caddyserver/caddy-1/caddyfile)
BuildRequires:  golang(github.com/lithammer/dedent)
BuildRequires:  golang(github.com/spf13/cobra)

%description
%{common_description}

%gopkg

%prep
%goprep
sed -i "s|github.com/caddyserver/caddy|github.com/caddyserver/caddy-1|" $(find . -name "*.go" -type f)

%build
for cmd in corefile-tool; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc corefile-tool/README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Wed Aug 10 2022 Maxwell G <gotmax@e.email> - 1.0.11-9
- Rebuild to fix FTBFS

* Thu Jul 21 2022 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.11-8
- Rebuilt for https://fedoraproject.org/wiki/Fedora_37_Mass_Rebuild

* Tue Jul 19 2022 Maxwell G <gotmax@e.email> - 1.0.11-7
- Rebuild for CVE-2022-{1705,32148,30631,30633,28131,30635,30632,30630,1962} in
  golang

* Sat Jun 18 2022 Robert-André Mauchin <zebob.m@gmail.com> - 1.0.11-6
- Rebuilt for CVE-2022-1996, CVE-2022-24675, CVE-2022-28327, CVE-2022-27191,
  CVE-2022-29526, CVE-2022-30629

* Sat Apr 16 2022 Fabio Alessandro Locati <me@fale.io> - 1.0.11-5
- Rebuilt for CVE-2022-27191

* Thu Jan 20 2022 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.11-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_36_Mass_Rebuild

* Thu Jul 22 2021 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.11-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_35_Mass_Rebuild

* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.11-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Fri Jan 15 17:56:15 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 1.0.11-1
- Update to 1.0.11

* Tue Aug 18 21:39:36 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 1.0.10-1
- Initial package
