## START: Set by rpmautospec
%define autorelease(e:s:pb:) %{?-p:0.}%{lua:
    release_number = 2;
    base_release_number = tonumber(rpm.expand("%{?-b*}%{!?-b:1}"));
    print(release_number + base_release_number - 1);
}%{?-e:.%{-e*}}%{?-s:.%{-s*}}%{?dist}
## END: Set by rpmautospec

# Generated by go2rpm 1.5.0
# Needs a mariadb instance
%bcond_with check

# https://github.com/planetscale/tengo
%global goipath         github.com/planetscale/tengo
Version:                0.10.1~ps.v6~vitess

%gometa

%global extractdir      %(echo %{extractdir} | sed -e 's/~/-/g')
%global gosource        %(echo %{gosource} | sed -e 's/~/-/g')

%global common_description %{expand:
Go La Tengo: a MySQL automation library.}

%global golicenses      LICENSE NOTICE
%global godocs          CONTRIBUTING.md README.md

Name:           %{goname}
Release:        %autorelease.1
Summary:        Go La Tengo: a MySQL automation library

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/fsouza/go-dockerclient)
BuildRequires:  golang(github.com/go-sql-driver/mysql)
BuildRequires:  golang(github.com/jmoiron/sqlx)
BuildRequires:  golang(github.com/nozzle/throttler)
BuildRequires:  golang(github.com/pmezard/go-difflib/difflib)
BuildRequires:  golang(github.com/VividCortex/mysqlerr)
BuildRequires:  golang(golang.org/x/sync/errgroup)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sat Jan 20 2024 Fedora Release Engineering <releng@fedoraproject.org> - 0.10.1~ps.v6~vitess-2.1
- Rebuilt for https://fedoraproject.org/wiki/Fedora_40_Mass_Rebuild

* Thu Aug 05 2021 Robert-André Mauchin <zebob.m@gmail.com> 0.10.1~ps.v6~vitess-2
- Uncommitted changes

* Thu Aug 05 2021 Robert-André Mauchin <zebob.m@gmail.com> 0.10.1~ps.v6~vitess-1
- Initial release
