# Generated by go2rpm
%bcond_without check

# https://github.com/ianlancetaylor/cgosymbolizer
%global goipath         github.com/ianlancetaylor/cgosymbolizer
%global commit          7acc97e5361482d9d04a9d2221fcdc5d25b72e9c

%gometa

%global common_description %{expand:
A Go package that can be used to convert cgo function pointers into useful
backtrace information.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.11%{?dist}
Summary:        Experimental symbolizer for cgo backtraces

License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Jul 20 2023 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.11
- Rebuilt for https://fedoraproject.org/wiki/Fedora_39_Mass_Rebuild

* Thu Jan 19 2023 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.10
- Rebuilt for https://fedoraproject.org/wiki/Fedora_38_Mass_Rebuild

* Thu Jul 21 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.9
- Rebuilt for https://fedoraproject.org/wiki/Fedora_37_Mass_Rebuild

* Thu Jan 20 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.8
- Rebuilt for https://fedoraproject.org/wiki/Fedora_36_Mass_Rebuild

* Thu Jul 22 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.7
- Rebuilt for https://fedoraproject.org/wiki/Fedora_35_Mass_Rebuild

* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.6
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Sat Jan 09 21:26:48 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 0-0.5.20210109git7acc97e
- Bump to 7acc97e5361482d9d04a9d2221fcdc5d25b72e9c

* Mon Jul 27 23:06:24 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 0-0.4.20200727gitbe1b05b
- Bump to commit be1b05b0b2790e3d9d080d29bd918304bbd35a2b

* Wed Jan 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Thu Jul 25 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Wed May 15 19:02:31 CEST 2019 Robert-André Mauchin <zebob.m@gmail.com> - 0-0.1.20190701gitf5072df
- Initial package
