# Generated by go2rpm
%bcond_without check

# https://github.com/coreos/go-oidc
%global goipath         github.com/coreos/go-oidc
Version:                3.0.0

%gometa

%global goaltipaths     github.com/coreos/go-oidc/v3

%global common_description %{expand:
A Go OpenID Connect client.}

%global golicenses      LICENSE NOTICE
%global godocs          example CONTRIBUTING.md README.md code-of-conduct.md

%global gosupfiles      glide.lock glide.yaml

Name:           %{goname}
Release:        %autorelease
Summary:        Go OpenID Connect client

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}
Source1:        glide.lock
Source2:        glide.yaml

BuildRequires:  golang(golang.org/x/net/context)
BuildRequires:  golang(golang.org/x/oauth2)
BuildRequires:  golang(gopkg.in/square/go-jose.v2)

%description
%{common_description}

%gopkg

%prep
%goprep
cp %{S:1} %{S:2} .

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
