# Generated by go2rpm 1
%bcond_without check

# https://github.com/jcmturner/gokrb5
%global goipath         gopkg.in/jcmturner/gokrb5.v7
%global forgeurl        https://github.com/jcmturner/gokrb5
Version:                7.5.0

%gometa


%global goipathsex0     gopkg.in/jcmturner/gokrb5.v7/v8

%global common_description %{expand:
Pure Go Kerberos library for clients and services.}

%global golicenses      LICENSE
%global godocs          examples CONTRIBUTING.md README.md USAGE.md

Name:           %{goname}
Release:        8%{?dist}
Summary:        Pure Go Kerberos library for clients and services

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/hashicorp/go-uuid)
BuildRequires:  golang(github.com/jcmturner/gofork/encoding/asn1)
BuildRequires:  golang(github.com/jcmturner/gofork/x/crypto/pbkdf2)
BuildRequires:  golang(golang.org/x/crypto/md4)
BuildRequires:  golang(golang.org/x/crypto/pbkdf2)
BuildRequires:  golang(gopkg.in/jcmturner/aescts.v1)
BuildRequires:  golang(gopkg.in/jcmturner/dnsutils.v1)
BuildRequires:  golang(gopkg.in/jcmturner/goidentity.v3)
BuildRequires:  golang(gopkg.in/jcmturner/rpc.v1/mstypes)
BuildRequires:  golang(gopkg.in/jcmturner/rpc.v1/ndr)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep
rm -rf v8/

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sat Jan 20 2024 Fedora Release Engineering <releng@fedoraproject.org> - 7.5.0-8
- Rebuilt for https://fedoraproject.org/wiki/Fedora_40_Mass_Rebuild

* Thu Jul 20 2023 Fedora Release Engineering <releng@fedoraproject.org> - 7.5.0-7
- Rebuilt for https://fedoraproject.org/wiki/Fedora_39_Mass_Rebuild

* Thu Jan 19 2023 Fedora Release Engineering <releng@fedoraproject.org> - 7.5.0-6
- Rebuilt for https://fedoraproject.org/wiki/Fedora_38_Mass_Rebuild

* Thu Jul 21 2022 Fedora Release Engineering <releng@fedoraproject.org> - 7.5.0-5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_37_Mass_Rebuild

* Thu Jan 20 2022 Fedora Release Engineering <releng@fedoraproject.org> - 7.5.0-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_36_Mass_Rebuild

* Thu Jul 22 2021 Fedora Release Engineering <releng@fedoraproject.org> - 7.5.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_35_Mass_Rebuild

* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 7.5.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Sun Aug 02 18:16:50 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 7.5.0-1
- Initial package
