# Generated by go2rpm 1.3

# https://github.com/twpayne/go-kml
%global goipath         github.com/twpayne/go-kml
Version:                1.5.2

%gometa

%global common_description %{expand:
Package Kml provides convenince methods for creating and writing KML documents.}

%global golicenses      LICENSE
%global godocs          examples README.md

Name:           %{goname}
Release:        4%{?dist}
Summary:        Convenince methods for creating and writing KML documents

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/Masterminds/sprig)
BuildRequires:  golang(github.com/twpayne/go-polyline)
BuildRequires:  golang(github.com/twpayne/go-waypoint)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Jul 21 2022 Fedora Release Engineering <releng@fedoraproject.org> - 1.5.2-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_37_Mass_Rebuild

* Thu Jan 20 2022 Fedora Release Engineering <releng@fedoraproject.org> - 1.5.2-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_36_Mass_Rebuild

* Thu Jul 22 2021 Fedora Release Engineering <releng@fedoraproject.org> - 1.5.2-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_35_Mass_Rebuild

* Thu Jan 28 23:30:29 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 1.5.2-1
- Initial package
