# Generated by go2rpm 1.9.0
%bcond_without check

# https://github.com/uber/mock
%global goipath         go.uber.org/mock
%global forgeurl        https://github.com/uber/mock
Version:                0.2.0

%gometa -f


%global common_description %{expand:
Mocking framework for the Go programming language.}

%global golicenses      LICENSE
%global godocs          AUTHORS CHANGELOG.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Mocking framework for the Go programming language

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in mockgen; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc AUTHORS CHANGELOG.md README.md
%{_bindir}/mockgen

%gopkgfiles

%changelog
%autochangelog
