# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/golang/term
%global goipath         golang.org/x/term
%global forgeurl        https://github.com/golang/term
%global commit          03fcf44c2211dcd5eb77510b5f7c1fb02d6ded50

%gometa

%global common_description %{expand:
Go terminal and console support.}

%global golicenses      LICENSE PATENTS
%global godocs          AUTHORS CONTRIBUTING.md CONTRIBUTORS README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Go terminal and console support

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(golang.org/x/sys/unix)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
