# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/shirou/gopsutil
%global goipath         github.com/shirou/gopsutil
Version:                3.21.6

%gometa

%global common_description %{expand:
This is a port of psutil (https://github.com/giampaolo/psutil). The challenge is
porting all psutil functions on some architectures.}

%global golicenses      LICENSE
%global godocs          README.rst

Name:           %{goname}
Release:        %autorelease
Summary:        Psutil for golang

License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/tklauser/go-sysconf)
BuildRequires:  golang(golang.org/x/sys/unix)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
# host: needs access to /var/run
# net: needs network
%gocheck -d cpu -d disk -d host -d net -d process -d v3/cpu -d v3/disk -d v3/host -d v3/net -d v3/process
%endif

%gopkgfiles

%changelog
%autochangelog
