# Generated by go2rpm 1
# Tests need to be set up: https://github.com/jackc/pgx#testing
%bcond_with check

# https://github.com/jackc/pgx
%global goipath         github.com/jackc/pgx-3
%global forgeurl        https://github.com/jackc/pgx
Version:                3.6.2

%gometa

%global goname golang-github-jackc-pgx-3
%global godevelname golang-github-jackc-pgx-devel-3


%global common_description %{expand:
PostgreSQL driver and toolkit for Go.}

%global golicenses      LICENSE
%global godocs          examples CHANGELOG.md README.md

Name:           %{goname}
Release:        6%{?dist}
Summary:        PostgreSQL driver and toolkit for Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/gofrs/uuid)
BuildRequires:  golang(github.com/lib/pq)
BuildRequires:  golang(github.com/pkg/errors)
BuildRequires:  golang(github.com/rs/zerolog)
BuildRequires:  golang(github.com/satori/go.uuid)
BuildRequires:  golang(github.com/shopspring/decimal)
BuildRequires:  golang(github.com/sirupsen/logrus)
BuildRequires:  golang(go.uber.org/zap)
BuildRequires:  golang(go.uber.org/zap/zapcore)
BuildRequires:  golang(golang.org/x/crypto/pbkdf2)
BuildRequires:  golang(golang.org/x/text/secure/precis)
BuildRequires:  golang(gopkg.in/inconshreveable/log15.v2)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/cockroachdb/apd)
BuildRequires:  golang(github.com/jackc/fake)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep
sed -i 's|github.com/jackc/pgx|github.com/jackc/pgx-3|' $(find . -iname "*.go" -type f)

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Jan 19 2023 Fedora Release Engineering <releng@fedoraproject.org> - 3.6.2-6
- Rebuilt for https://fedoraproject.org/wiki/Fedora_38_Mass_Rebuild

* Thu Jul 21 2022 Fedora Release Engineering <releng@fedoraproject.org> - 3.6.2-5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_37_Mass_Rebuild

* Thu Jan 20 2022 Fedora Release Engineering <releng@fedoraproject.org> - 3.6.2-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_36_Mass_Rebuild

* Thu Jul 22 2021 Fedora Release Engineering <releng@fedoraproject.org> - 3.6.2-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_35_Mass_Rebuild

* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 3.6.2-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Wed Sep 09 17:38:32 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 3.6.2-1
- Initial package
