# Generated by go2rpm 1
%bcond_without check
%bcond_with network

# https://github.com/henvic/httpretty
%global goipath         github.com/henvic/httpretty
Version:                0.1.0

%gometa

%global common_description %{expand:
Package httpretty prints the HTTP requests you make with Go pretty on your
terminal.}

%global golicenses      LICENSE.md
%global godocs          example README.md CONTRIBUTING.md

Name:           %{goname}
Release:        %autorelease
Summary:        Prints the HTTP requests on your terminal

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with network}
%if %{with check}
%check
%gocheck
%endif
%endif

%gopkgfiles

%changelog
%autochangelog

