# Generated by go2rpm
%bcond_without check

# https://github.com/paulbellamy/ratecounter
%global goipath         github.com/paulbellamy/ratecounter
Version:                0.2.0
%global commit          a05fe2ccb7bd521822002ddbd47903ac1ed1eb63

%gometa

%global common_description %{expand:
Package Ratecounter provides a thread-safe rate-counter, for tracking counts in
an interval.}

%global golicenses      LICENSE
%global godocs          CONTRIBUTORS.md README.md

Name:           %{goname}
Release:        12%{?dist}
Summary:        Thread-safe ratecounter implementation in Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
for test in "TestRateCounterHighResolution" \
; do
awk -i inplace '/^func.*'"$test"'\(/ { print; print "\tt.Skip(\"disabled failing test\")"; next}1' $(grep -rl $test)
done
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Jan 19 2023 Fedora Release Engineering <releng@fedoraproject.org> - 0.2.0-12
- Rebuilt for https://fedoraproject.org/wiki/Fedora_38_Mass_Rebuild

* Thu Jul 21 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0.2.0-11
- Rebuilt for https://fedoraproject.org/wiki/Fedora_37_Mass_Rebuild

* Thu Jan 20 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0.2.0-10
- Rebuilt for https://fedoraproject.org/wiki/Fedora_36_Mass_Rebuild

* Thu Aug 26 2021 Fabian Affolter <mail@fabian-affolter.ch> - 0.2.0-9
- Rebuilt (closes rhbz#1987536)

* Thu Jul 22 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.2.0-8
- Rebuilt for https://fedoraproject.org/wiki/Fedora_35_Mass_Rebuild

* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.2.0-7
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Sun Jan 24 20:10:35 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 0.2.0-6.20210124gita05fe2c
- Bump to commit a05fe2ccb7bd521822002ddbd47903ac1ed1eb63
- Temporarly fix FTBFS by disabling TestRateCounterHighResolution

* Sat Aug 01 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.2.0-6
- Second attempt - Rebuilt for
  https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Mon Jul 27 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.2.0-5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Sun Feb 02 01:02:10 CET 2020 Robert-André Mauchin <zebob.m@gmail.com> - 0.2.0-4.20200202gita21a441
- Bump to commit a21a441076fe606cdec3e1914ce8c27cfde47645

* Wed Jan 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.2.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Thu Jul 25 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.2.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Mon Apr 29 14:27:25 CEST 2019 Robert-André Mauchin <zebob.m@gmail.com> - 0.2.0-1
- Initial package
