# Generated by go2rpm 1
%bcond_without check

# https://github.com/projectdiscovery/fdmax
%global goipath         github.com/projectdiscovery/fdmax
Version:                0.0.3

%gometa

%global common_description %{expand:
Small Helper Library to increase automatically the file descriptors limits for
the current process.}

%global godocs          example README.md

Name:           %{goname}
Release:        5%{?dist}
Summary:        Helper Library to increase automatically the file descriptors

License:        MIT

URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(golang.org/x/sys/unix)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Jul 21 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0.0.3-5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_37_Mass_Rebuild

* Thu Jan 20 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0.0.3-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_36_Mass_Rebuild

* Thu Jul 22 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.0.3-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_35_Mass_Rebuild

* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.0.3-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Thu Jan 21 19:35:41 CET 2021 Robert-André Mauchin <zebob.m@gmail.com> - 0.0.3-1
- Update to 0.0.3

* Sun Nov 08 2020 Fabian Affolter <mail@fabian-affolter.ch> - 0.0.2-2
- Add license detail (#1881585)

* Tue Sep 22 2020 Fabian Affolter <mail@fabian-affolter.ch> - 0.0.2-1
- Initial package
