# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/prometheus/common
%global goipath         github.com/prometheus/common
Version:                0.35.0

%gometa

%global common_description %{expand:
This repository contains Go libraries that are shared across Prometheus
components and libraries.

 - config: Common configuration structures
 - expfmt: Decoding and encoding for the exposition format
 - log: A logging wrapper around logrus
 - model: Shared data structures
 - route: A routing wrapper around httprouter using context.Context
 - version: Version information and metrics}

# This should be removed in Fedora 39
%global godevelheader0  %{expand:
# This package used to be split up to solve a bootstrapping issue.
# golang-github-prometheus-common-promlog-devel has since been merged with
# the main -devel package, so we need this to ensure a smooth update path.
# See https://bugzilla.redhat.com/2109630
Provides: golang-github-prometheus-common-promlog-devel = %{?epoch:epoch:}%{version}-%{release}
Obsoletes: golang-github-prometheus-common-promlog-devel < 0.30.0-6
}
%global golicenses      LICENSE NOTICE
%global godocs          CONTRIBUTING.md MAINTAINERS.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Go libraries shared across prometheus components and libraries

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}


%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
%check
# Go 1.18 deprecated SHA1-RSA
export GODEBUG=x509sha1=1
%gocheck
%endif
%endif

%gopkgfiles

%changelog
%autochangelog
