# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/go-sql-driver/mysql
%global goipath         github.com/go-sql-driver/mysql
Version:                1.6.0

%gometa

%global common_description %{expand:
A MySQL-Driver for Go's database/sql package.}

%global golicenses      LICENSE
%global godocs          AUTHORS CHANGELOG.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        MySQL driver for Go's database/sql package

License:        MPL-2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
