# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/Masterminds/squirrel
%global goipath         github.com/Masterminds/squirrel
Version:                1.5.1

%gometa

%global common_description %{expand:
Fluent SQL generation for golang.}

%global golicenses      LICENSE.txt
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Fluent SQL generation for golang

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/lann/builder)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/go-sql-driver/mysql)
BuildRequires:  golang(github.com/lib/pq)
BuildRequires:  golang(github.com/mattn/go-sqlite3)
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
