# Generated by go2rpm 1
# Needs network and pgsql
%bcond_with check

# https://github.com/jackc/pgtype
%global goipath         github.com/jackc/pgtype
Version:                1.6.2

%gometa

%global goipathsex      github.com/jackc/pgtype/testutil

%global common_description %{expand:
pgtype implements Go types for over 70 PostgreSQL types. pgtype is the type
system underlying the https://github.com/jackc/pgx PostgreSQL driver. These
types support the binary format for enhanced performance with pgx. They also
support the database/sql Scan and Value interfaces and can be used with
https://github.com/lib/pq.}

%global golicenses      LICENSE
%global godocs          CHANGELOG.md README.md pgxtype/README.md

Name:           %{goname}
Release:        9%{?dist}
Summary:        Go types for over 70 PostgreSQL types

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/gofrs/uuid)
BuildRequires:  golang(github.com/jackc/pgconn)
BuildRequires:  golang(github.com/jackc/pgio)
BuildRequires:  golang(github.com/jackc/pgx/v4)
BuildRequires:  golang(github.com/jackc/pgx/v4/stdlib)
BuildRequires:  golang(github.com/lib/pq)
BuildRequires:  golang(github.com/shopspring/decimal)
BuildRequires:  golang(golang.org/x/xerrors)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Wed Jan 24 2024 Fedora Release Engineering <releng@fedoraproject.org> - 1.6.2-9
- Rebuilt for https://fedoraproject.org/wiki/Fedora_40_Mass_Rebuild

* Sat Jan 20 2024 Fedora Release Engineering <releng@fedoraproject.org> - 1.6.2-8
- Rebuilt for https://fedoraproject.org/wiki/Fedora_40_Mass_Rebuild

* Thu Jul 20 2023 Fedora Release Engineering <releng@fedoraproject.org> - 1.6.2-7
- Rebuilt for https://fedoraproject.org/wiki/Fedora_39_Mass_Rebuild

* Thu Jan 19 2023 Fedora Release Engineering <releng@fedoraproject.org> - 1.6.2-6
- Rebuilt for https://fedoraproject.org/wiki/Fedora_38_Mass_Rebuild

* Thu Jul 21 2022 Fedora Release Engineering <releng@fedoraproject.org> - 1.6.2-5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_37_Mass_Rebuild

* Thu Jan 20 2022 Fedora Release Engineering <releng@fedoraproject.org> - 1.6.2-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_36_Mass_Rebuild

* Thu Jul 22 2021 Fedora Release Engineering <releng@fedoraproject.org> - 1.6.2-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_35_Mass_Rebuild

* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 1.6.2-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Sat Jul 25 13:51:09 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 1.4.2-1
- Initial package
