# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/uber-go/automaxprocs
%global goipath         go.uber.org/automaxprocs
%global forgeurl        https://github.com/uber-go/automaxprocs
Version:                1.5.2

%gometa -f


%global goaltipaths     github.com/uber-go/automaxprocs

%global common_description %{expand:
Automatically set GOMAXPROCS to match Linux container CPU quota.}

%global golicenses      LICENSE
%global godocs          CHANGELOG.md CODE_OF_CONDUCT.md CONTRIBUTING.md\\\
                        README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Automatically set GOMAXPROCS to match Linux container CPU quota

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
