Name:           perl-String-TtyLength
Version:        0.03
Release:        6%{?dist}
Summary:        Length or width of string excluding ANSI tty codes
License:        GPL+ or Artistic
URL:            https://metacpan.org/pod/String::TtyLength
Source0:        https://cpan.metacpan.org/authors/id/N/NE/NEILB/String-TtyLength-%{version}.tar.gz
BuildArch:      noarch
# build requirements
BuildRequires:  make
BuildRequires:  perl-generators
BuildRequires:  perl-interpreter
BuildRequires:  perl(ExtUtils::MakeMaker) >= 6.76
# runtime requirements
BuildRequires:  perl(Exporter)
BuildRequires:  perl(parent)
BuildRequires:  perl(strict)
BuildRequires:  perl(Unicode::EastAsianWidth) >= 12.0
BuildRequires:  perl(warnings)
# test requirements
BuildRequires:  perl(Test2::V0)
BuildRequires:  perl(utf8)
Requires:       perl(:MODULE_COMPAT_%(eval "`/usr/bin/perl -V:version`"; echo $version))

%{?perl_default_filter}

%description
This module provides two functions which tell you the length and width
of a string as it will appear on a terminal (tty), excluding any ANSI
escape codes.

%prep
%setup -q -n String-TtyLength-%{version}

%build
/usr/bin/perl Makefile.PL INSTALLDIRS=vendor NO_PACKLIST=1 NO_PERLLOCAL=1
%{make_build}

%install
%{make_install}
%{_fixperms} $RPM_BUILD_ROOT/*

%check
%{make_build} test

%files
%doc Changes README
%license LICENSE
%{perl_vendorlib}/String*
%{_mandir}/man3/String*

%changelog
* Fri Jul 22 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0.03-6
- Rebuilt for https://fedoraproject.org/wiki/Fedora_37_Mass_Rebuild

* Wed Jun 01 2022 Jitka Plesnikova <jplesnik@redhat.com> - 0.03-5
- Perl 5.36 rebuild

* Fri Jan 21 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0.03-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_36_Mass_Rebuild

* Thu Jul 22 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.03-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_35_Mass_Rebuild

* Fri May 21 2021 Jitka Plesnikova <jplesnik@redhat.com> - 0.03-2
- Perl 5.34 rebuild

* Sat May 01 2021 Emmanuel Seyman <emmanuel@seyman.fr> - 0.03-1
- Update to 0.03

* Wed Jan 27 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.02-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Sun Sep 13 2020 Emmanuel Seyman <emmanuel@seyman.fr> - 0.02-1
- Initial specfile, based on the one autogenerated by cpanspec 1.78.
