# Generated by rust2rpm 24
%bcond_without check

%global crate clang-tidy-sarif

Name:           rust-clang-tidy-sarif
Version:        0.4.1
Release:        %autorelease
Summary:        Convert clang-tidy output to SARIF

License:        MIT
URL:            https://crates.io/crates/clang-tidy-sarif
Source:         %{crates_source}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Convert clang-tidy output to SARIF.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# (MIT OR Apache-2.0) AND Unicode-DFS-2016
# Apache-2.0 OR BSL-1.0
# Apache-2.0 OR MIT
# Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT
# MIT
# Unlicense OR MIT
License:        ((MIT OR Apache-2.0) AND Unicode-DFS-2016) AND (Apache-2.0 OR BSL-1.0) AND (Apache-2.0 OR MIT) AND (Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT) AND MIT AND (Unlicense OR MIT)
# LICENSE.dependencies contains a full license breakdown
# based on example from rpms/rust-git-delta

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/clang-tidy-sarif

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%cargo_license_summary
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
