# Generated by rust2rpm 24
# * tests can only be run in-tree
%bcond_with check
%global debug_package %{nil}

%global crate actix-http

Name:           rust-actix-http
Version:        3.4.0
Release:        %autorelease
Summary:        HTTP primitives for the Actix ecosystem

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/actix-http
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
# * drop unused support for rustls
Patch:          actix-http-fix-metadata.diff

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
HTTP primitives for the Actix ecosystem.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGES.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+__compress-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+__compress-devel %{_description}

This package contains library source intended for building other packages which
use the "__compress" feature of the "%{crate}" crate.

%files       -n %{name}+__compress-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+actix-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+actix-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "actix-tls" feature of the "%{crate}" crate.

%files       -n %{name}+actix-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+base64-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+base64-devel %{_description}

This package contains library source intended for building other packages which
use the "base64" feature of the "%{crate}" crate.

%files       -n %{name}+base64-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+brotli-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+brotli-devel %{_description}

This package contains library source intended for building other packages which
use the "brotli" feature of the "%{crate}" crate.

%files       -n %{name}+brotli-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+compress-brotli-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+compress-brotli-devel %{_description}

This package contains library source intended for building other packages which
use the "compress-brotli" feature of the "%{crate}" crate.

%files       -n %{name}+compress-brotli-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+compress-gzip-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+compress-gzip-devel %{_description}

This package contains library source intended for building other packages which
use the "compress-gzip" feature of the "%{crate}" crate.

%files       -n %{name}+compress-gzip-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+compress-zstd-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+compress-zstd-devel %{_description}

This package contains library source intended for building other packages which
use the "compress-zstd" feature of the "%{crate}" crate.

%files       -n %{name}+compress-zstd-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+flate2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+flate2-devel %{_description}

This package contains library source intended for building other packages which
use the "flate2" feature of the "%{crate}" crate.

%files       -n %{name}+flate2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+h2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+h2-devel %{_description}

This package contains library source intended for building other packages which
use the "h2" feature of the "%{crate}" crate.

%files       -n %{name}+h2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+http2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+http2-devel %{_description}

This package contains library source intended for building other packages which
use the "http2" feature of the "%{crate}" crate.

%files       -n %{name}+http2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+local-channel-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+local-channel-devel %{_description}

This package contains library source intended for building other packages which
use the "local-channel" feature of the "%{crate}" crate.

%files       -n %{name}+local-channel-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+openssl-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+openssl-devel %{_description}

This package contains library source intended for building other packages which
use the "openssl" feature of the "%{crate}" crate.

%files       -n %{name}+openssl-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rand-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rand-devel %{_description}

This package contains library source intended for building other packages which
use the "rand" feature of the "%{crate}" crate.

%files       -n %{name}+rand-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sha1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sha1-devel %{_description}

This package contains library source intended for building other packages which
use the "sha1" feature of the "%{crate}" crate.

%files       -n %{name}+sha1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ws-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ws-devel %{_description}

This package contains library source intended for building other packages which
use the "ws" feature of the "%{crate}" crate.

%files       -n %{name}+ws-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+zstd-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+zstd-devel %{_description}

This package contains library source intended for building other packages which
use the "zstd" feature of the "%{crate}" crate.

%files       -n %{name}+zstd-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
