# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}

%global crate terminal-light

Name:           rust-terminal-light
Version:        1.1.1
Release:        %autorelease
Summary:        Tells you whether your terminal is dark or light

License:        MIT
URL:            https://crates.io/crates/terminal-light
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
# * prevent unused binary from being built and shipped
# * bump crossterm dependency from 0.23 to 0.26
Patch:          terminal-light-fix-metadata.diff

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Tells you whether your terminal is dark or light.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
