# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}

%global crate json_to_table

Name:           rust-json_to_table
Version:        0.3.1
Release:        %autorelease
Summary:        Libary for pretty print JSON as a table

License:        MIT
URL:            https://crates.io/crates/json_to_table
Source:         %{crates_source}
# License files added after 0.3.1 was released
Source1:        https://raw.githubusercontent.com/zhiburt/tabled/9fcb1cd669cb73934d2c9fb81af4187897670a82/json_to_table/LICENSE-MIT

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
A libary for pretty print JSON as a table.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+color-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+color-devel %{_description}

This package contains library source intended for building other packages which
use the "color" feature of the "%{crate}" crate.

%files       -n %{name}+color-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
cp -p %{SOURCE1} .
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
