# Generated by rust2rpm 17
%bcond_without check
%global debug_package %{nil}

%global crate standback

Name:           rust-%{crate}
Version:        0.2.17
Release:        4%{?dist}
Summary:        New standard library, old compiler

# Upstream license specification: MIT OR Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/standback
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
New standard library, old compiler.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-Apache LICENSE-MIT
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages
which use "std" feature of "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Jul 23 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0.2.17-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_37_Mass_Rebuild

* Fri Jan 21 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0.2.17-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_36_Mass_Rebuild

* Fri Jul 23 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.2.17-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_35_Mass_Rebuild

* Fri Mar 26 2021 Fabio Valentini <decathorpe@gmail.com> - 0.2.17-1
- Update to version 0.2.17.
- Fixes RHBZ#1941394

* Sun Mar 21 2021 Fabio Valentini <decathorpe@gmail.com> - 0.2.16-1
- Update to version 0.2.16.
- Fixes RHBZ#1940816

* Sun Feb 07 2021 Fabio Valentini <decathorpe@gmail.com> - 0.2.15-1
- Update to version 0.2.15.
- Fixes RHBZ#1925376

* Wed Jan 27 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.2.14-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Wed Dec 30 10:38:00 CET 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.2.14-1
- Update to 0.2.14 (Fixes: RHBZ#1911598)

* Thu Nov 19 2020 Fabio Valentini <decathorpe@gmail.com> - 0.2.13-1
- Update to version 0.2.13.
- Fixes RHBZ#1898424

* Fri Nov 06 2020 Fabio Valentini <decathorpe@gmail.com> - 0.2.11-1
- Update to version 0.2.11.
- Fixes RHBZ#1886212

* Wed Aug 26 2020 Josh Stone <jistone@redhat.com> - 0.2.10-1
- Update to 0.2.10

* Sat Aug 01 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.2.9-3
- Second attempt - Rebuilt for
  https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Wed Jul 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.2.9-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Fri Jun 05 2020 Josh Stone <jistone@redhat.com> - 0.2.9-1
- Update to 0.2.9

* Wed Apr 29 2020 Josh Stone <jistone@redhat.com> - 0.2.8-1
- Update to 0.2.8

* Fri Apr 17 16:40:46 PDT 2020 Josh Stone <jistone@redhat.com> - 0.2.2-1
- Initial package
