# Generated by rust2rpm 18
%bcond_without check
%global debug_package %{nil}

%global crate i18n-embed-impl

Name:           rust-%{crate}
Version:        0.8.0
Release:        3%{?dist}
Summary:        Macro implementations for i18n-embed

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/i18n-embed-impl
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Macro implementations for i18n-embed.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+find-crate-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+find-crate-devel %{_description}

This package contains library source intended for building other packages
which use "find-crate" feature of "%{crate}" crate.

%files       -n %{name}+find-crate-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+fluent-system-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+fluent-system-devel %{_description}

This package contains library source intended for building other packages
which use "fluent-system" feature of "%{crate}" crate.

%files       -n %{name}+fluent-system-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+gettext-system-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gettext-system-devel %{_description}

This package contains library source intended for building other packages
which use "gettext-system" feature of "%{crate}" crate.

%files       -n %{name}+gettext-system-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+i18n-config-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+i18n-config-devel %{_description}

This package contains library source intended for building other packages
which use "i18n-config" feature of "%{crate}" crate.

%files       -n %{name}+i18n-config-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+quote-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+quote-devel %{_description}

This package contains library source intended for building other packages
which use "quote" feature of "%{crate}" crate.

%files       -n %{name}+quote-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -f fluent-system

%build
%cargo_build -f fluent-system

%install
%cargo_install -f fluent-system

%if %{with check}
%check
%cargo_test -f fluent-system
%endif

%changelog
* Sat Jul 23 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0.8.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_37_Mass_Rebuild

* Fri Jan 21 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0.8.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_36_Mass_Rebuild

* Mon Nov 22 2021 Link Dupont <linkdupont@fedoraproject.org> - 0.8.0-1
- New upstream version

* Mon Oct 04 2021 Link Dupont <linkdupont@fedoraproject.org> - 0.7.0-1
- Initial package
