# Generated by rust2rpm 25
%bcond_without check
%global debug_package %{nil}

%global crate reqwest

Name:           rust-reqwest
Version:        0.11.22
Release:        %autorelease
Summary:        Higher level HTTP client library

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/reqwest
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          reqwest-fix-metadata-auto.diff

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Higher level HTTP client library.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+__internal_proxy_sys_no_cache-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+__internal_proxy_sys_no_cache-devel %{_description}

This package contains library source intended for building other packages which
use the "__internal_proxy_sys_no_cache" feature of the "%{crate}" crate.

%files       -n %{name}+__internal_proxy_sys_no_cache-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+__tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+__tls-devel %{_description}

This package contains library source intended for building other packages which
use the "__tls" feature of the "%{crate}" crate.

%files       -n %{name}+__tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+async-compression-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+async-compression-devel %{_description}

This package contains library source intended for building other packages which
use the "async-compression" feature of the "%{crate}" crate.

%files       -n %{name}+async-compression-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+blocking-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+blocking-devel %{_description}

This package contains library source intended for building other packages which
use the "blocking" feature of the "%{crate}" crate.

%files       -n %{name}+blocking-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+brotli-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+brotli-devel %{_description}

This package contains library source intended for building other packages which
use the "brotli" feature of the "%{crate}" crate.

%files       -n %{name}+brotli-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cookie_crate-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cookie_crate-devel %{_description}

This package contains library source intended for building other packages which
use the "cookie_crate" feature of the "%{crate}" crate.

%files       -n %{name}+cookie_crate-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cookie_store-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cookie_store-devel %{_description}

This package contains library source intended for building other packages which
use the "cookie_store" feature of the "%{crate}" crate.

%files       -n %{name}+cookie_store-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cookies-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cookies-devel %{_description}

This package contains library source intended for building other packages which
use the "cookies" feature of the "%{crate}" crate.

%files       -n %{name}+cookies-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+default-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "default-tls" feature of the "%{crate}" crate.

%files       -n %{name}+default-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+deflate-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+deflate-devel %{_description}

This package contains library source intended for building other packages which
use the "deflate" feature of the "%{crate}" crate.

%files       -n %{name}+deflate-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gzip-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gzip-devel %{_description}

This package contains library source intended for building other packages which
use the "gzip" feature of the "%{crate}" crate.

%files       -n %{name}+gzip-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+hyper-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hyper-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "hyper-tls" feature of the "%{crate}" crate.

%files       -n %{name}+hyper-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+json-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+json-devel %{_description}

This package contains library source intended for building other packages which
use the "json" feature of the "%{crate}" crate.

%files       -n %{name}+json-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mime_guess-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mime_guess-devel %{_description}

This package contains library source intended for building other packages which
use the "mime_guess" feature of the "%{crate}" crate.

%files       -n %{name}+mime_guess-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+multipart-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+multipart-devel %{_description}

This package contains library source intended for building other packages which
use the "multipart" feature of the "%{crate}" crate.

%files       -n %{name}+multipart-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+native-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+native-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "native-tls" feature of the "%{crate}" crate.

%files       -n %{name}+native-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+native-tls-alpn-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+native-tls-alpn-devel %{_description}

This package contains library source intended for building other packages which
use the "native-tls-alpn" feature of the "%{crate}" crate.

%files       -n %{name}+native-tls-alpn-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+native-tls-crate-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+native-tls-crate-devel %{_description}

This package contains library source intended for building other packages which
use the "native-tls-crate" feature of the "%{crate}" crate.

%files       -n %{name}+native-tls-crate-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde_json-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde_json-devel %{_description}

This package contains library source intended for building other packages which
use the "serde_json" feature of the "%{crate}" crate.

%files       -n %{name}+serde_json-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+socks-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+socks-devel %{_description}

This package contains library source intended for building other packages which
use the "socks" feature of the "%{crate}" crate.

%files       -n %{name}+socks-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+stream-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+stream-devel %{_description}

This package contains library source intended for building other packages which
use the "stream" feature of the "%{crate}" crate.

%files       -n %{name}+stream-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-native-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-native-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio-native-tls" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-native-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-socks-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-socks-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio-socks" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-socks-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-util-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-util-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio-util" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-util-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+trust-dns-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+trust-dns-devel %{_description}

This package contains library source intended for building other packages which
use the "trust-dns" feature of the "%{crate}" crate.

%files       -n %{name}+trust-dns-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+trust-dns-resolver-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+trust-dns-resolver-devel %{_description}

This package contains library source intended for building other packages which
use the "trust-dns-resolver" feature of the "%{crate}" crate.

%files       -n %{name}+trust-dns-resolver-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# * skip tests which require internet access
%cargo_test -- -- --exact --skip test_allowed_methods --skip test_badssl_modern --skip test_badssl_self_signed --skip test_tls_info
%endif

%changelog
%autochangelog
