# Generated by rust2rpm 23
%bcond_without check
%global debug_package %{nil}

%global crate vhost

Name:           rust-vhost
Version:        0.6.0
Release:        1%{?dist}
Summary:        Pure rust library for vdpa, vhost and vhost-user

License:        Apache-2.0 OR BSD-3-Clause
URL:            https://crates.io/crates/vhost
Source0:        %{crates_source}
Source1:        https://raw.githubusercontent.com/rust-vmm/vhost/main/LICENSE
Source2:        https://raw.githubusercontent.com/rust-vmm/vhost/main/LICENSE-BSD-3-Clause

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Pure rust library for vdpa, vhost and vhost-user.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%license %{crate_instdir}/LICENSE-BSD-3-Clause
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+vhost-kern-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+vhost-kern-devel %{_description}

This package contains library source intended for building other packages which
use the "vhost-kern" feature of the "%{crate}" crate.

%files       -n %{name}+vhost-kern-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+vhost-net-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+vhost-net-devel %{_description}

This package contains library source intended for building other packages which
use the "vhost-net" feature of the "%{crate}" crate.

%files       -n %{name}+vhost-net-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+vhost-user-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+vhost-user-devel %{_description}

This package contains library source intended for building other packages which
use the "vhost-user" feature of the "%{crate}" crate.

%files       -n %{name}+vhost-user-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+vhost-user-master-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+vhost-user-master-devel %{_description}

This package contains library source intended for building other packages which
use the "vhost-user-master" feature of the "%{crate}" crate.

%files       -n %{name}+vhost-user-master-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+vhost-user-slave-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+vhost-user-slave-devel %{_description}

This package contains library source intended for building other packages which
use the "vhost-user-slave" feature of the "%{crate}" crate.

%files       -n %{name}+vhost-user-slave-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+vhost-vdpa-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+vhost-vdpa-devel %{_description}

This package contains library source intended for building other packages which
use the "vhost-vdpa" feature of the "%{crate}" crate.

%files       -n %{name}+vhost-vdpa-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+vhost-vsock-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+vhost-vsock-devel %{_description}

This package contains library source intended for building other packages which
use the "vhost-vsock" feature of the "%{crate}" crate.

%files       -n %{name}+vhost-vsock-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep
cp %{SOURCE1} .
cp %{SOURCE2} .

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Wed Feb 08 2023 Sergio Lopez <slp@redhat.com> - 0.6.0-1
- Regenerate with rust2rpm 23
- Update to version 0.6.0
- Add license files, since crate has moved into a workspace

* Sat Jan 21 2023 Fedora Release Engineering <releng@fedoraproject.org> - 0.4.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_38_Mass_Rebuild

* Sat Jul 23 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0.4.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_37_Mass_Rebuild

* Wed Jun 01 2022 Sergio Lopez <slp@redhat.com> - 0.4.0-1
- Update to 0.4.0

* Thu Feb 17 2022 Sergio Lopez <slp@redhat.com> - 0.3.0-1
- Initial package
