# Generated by rust2rpm 17
%bcond_without check
%global debug_package %{nil}

%global crate virtio-bindings

Name:           rust-%{crate}
Version:        0.1.0
Release:        6%{?dist}
Summary:        Rust FFI bindings to virtio generated using bindgen

# Upstream license specification: BSD-3-Clause OR Apache-2.0
License:        BSD or ASL 2.0
URL:            https://crates.io/crates/virtio-bindings
Source:         %{crates_source}
# Initial patched metadata
# * Exclude unneeded files
Patch0:         virtio-bindings-fix-metadata.diff

ExclusiveArch:  x86_64 aarch64 ppc64le
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Rust FFI bindings to virtio generated using bindgen.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-APACHE LICENSE-BSD
%doc CHANGELOG.md CONTRIBUTING.md README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+virtio-v4_14_0-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+virtio-v4_14_0-devel %{_description}

This package contains library source intended for building other packages
which use "virtio-v4_14_0" feature of "%{crate}" crate.

%files       -n %{name}+virtio-v4_14_0-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+virtio-v5_0_0-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+virtio-v5_0_0-devel %{_description}

This package contains library source intended for building other packages
which use "virtio-v5_0_0" feature of "%{crate}" crate.

%files       -n %{name}+virtio-v5_0_0-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Jan 21 2023 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.0-6
- Rebuilt for https://fedoraproject.org/wiki/Fedora_38_Mass_Rebuild

* Sat Jul 23 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.0-5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_37_Mass_Rebuild

* Fri Jan 21 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.0-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_36_Mass_Rebuild

* Fri Jul 23 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_35_Mass_Rebuild

* Thu Jun 03 2021 Sergio Lopez <slp@redhat.com> - 0.1.0-2
- Exclude unsupported arches

* Fri May 07 2021 Sergio Lopez <slp@redhat.com> - 0.1.0-1
- Initial package
