# Generated by rust2rpm 16
%bcond_with check
%global debug_package %{nil}

%global crate version-sync

Name:           rust-%{crate}0.8
Version:        0.8.1
Release:        6%{?dist}
Summary:        Simple crate for ensuring that version numbers in README files are updated

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/version-sync
Source:         %{crates_source}
# Initial patched metadata
# * Update pulldown-cmark to 0.8
Patch0:         version-sync-fix-metadata.diff
# * Fix tests with toml 0.5.3+, https://github.com/mgeisler/version-sync/commit/33dc77fda8c5d993abee4e6c31c7526408877003
Patch0001:      0001-markdown_deps-handle-test-output-from-toml-0.5.3.patch
Patch0002:      0001-chore-Update-pulldown-cmark-to-0.7.patch

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Simple crate for ensuring that version numbers in README files are updated when
the crate version changes.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Jul 23 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0.8.1-6
- Rebuilt for https://fedoraproject.org/wiki/Fedora_37_Mass_Rebuild

* Fri Jan 21 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0.8.1-5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_36_Mass_Rebuild

* Fri Jul 23 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.8.1-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_35_Mass_Rebuild

* Wed Jan 27 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.8.1-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Fri Dec 25 12:01:49 CET 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.8.1-2
- Update pulldown-cmark to 0.8

* Sat Aug 29 19:44:45 CEST 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.8.1-1
- Initial package
