# Generated by rust2rpm 20
%bcond_without check
%global debug_package %{nil}

%global crate ignition-config

Name:           rust-%{crate}
Version:        0.2.0
Release:        %autorelease
Summary:        Data structures for reading/writing Ignition configs

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            https://crates.io/crates/ignition-config
Source:         %{crates_source}
# Disable development-only feature for regenerating sources
Patch0:         ignition-config-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%global _description %{expand:
Data structures for reading/writing Ignition configs.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
