# Generated by rust2rpm 24
# * missing dev-dependency: trycmd ^0.14
%bcond_with check
%global debug_package %{nil}

%global crate cargo-options

Name:           rust-cargo-options
Version:        0.6.0
Release:        %autorelease
Summary:        Reusable common Cargo command line options

License:        MIT
URL:            https://crates.io/crates/cargo-options
Source:         %{crates_source}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Reusable common Cargo command line options.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
