# Generated by rust2rpm 16

# missing dev-dependencies: crate(insta/default)
%bcond_with check
%global debug_package %{nil}

%global crate codespan-reporting
%global github_project  brendanzab/codespan

Name:           rust-%{crate}
Version:        0.11.1
Release:        5%{?dist}
Summary:        Beautiful diagnostic reporting for text-based programming languages

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            https://crates.io/crates/codespan-reporting
Source:         %{crates_source}
Source:         https://raw.githubusercontent.com/%{github_project}/v%{version}/README.md
Source:         https://raw.githubusercontent.com/%{github_project}/v%{version}/LICENSE

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Beautiful diagnostic reporting for text-based programming languages.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%{cargo_registry}/%{crate}-%{version_no_tilde}/
%doc        README.md
%license    LICENSE

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages
which use "serde" feature of "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+serialization-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serialization-devel %{_description}

This package contains library source intended for building other packages
which use "serialization" feature of "%{crate}" crate.

%files       -n %{name}+serialization-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep
cp -prt "${PWD}"    '%{SOURCE1}' '%{SOURCE2}'

%generate_buildrequires
%cargo_generate_buildrequires -a

%build
%cargo_build -a

%install
%cargo_install -a

%if %{with check}
%check
%cargo_test -a
%endif

%changelog
* Fri Jan 20 2023 Fedora Release Engineering <releng@fedoraproject.org> - 0.11.1-5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_38_Mass_Rebuild

* Sat Jul 23 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0.11.1-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_37_Mass_Rebuild

* Fri Jan 21 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0.11.1-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_36_Mass_Rebuild

* Fri Jul 23 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.11.1-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_35_Mass_Rebuild

* Mon Jun 07 2021 Jan Staněk <jstanek@redhat.com> - 0.11.1-1
- Upgrade to version 0.11.1
- Disable test suite by default (missing crate(insta/default))

* Fri Feb 05 2021 Jan Staněk <jstanek@redhat.com> - 0.9.5-2
- Import README.md and LICENSE from upstream git repository

* Mon Feb 01 11:50:43 CET 2021 Jan Staněk <jstanek@redhat.com> - 0.9.5-1
- Initial package
