# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}

%global crate smallstr

Name:           rust-smallstr
Version:        0.2.0
Release:        %autorelease
Summary:        String-like container based on smallvec

# Upstream license specification: MIT/Apache-2.0
License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/smallstr
Source0:        %{crates_source}
Source1:        https://github.com/murarth/smallstr/raw/93b8917/LICENSE-APACHE
Source2:        https://github.com/murarth/smallstr/raw/93b8917/LICENSE-MIT

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
String-like container based on smallvec.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ffi-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ffi-devel %{_description}

This package contains library source intended for building other packages which
use the "ffi" feature of the "%{crate}" crate.

%files       -n %{name}+ffi-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+union-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+union-devel %{_description}

This package contains library source intended for building other packages which
use the "union" feature of the "%{crate}" crate.

%files       -n %{name}+union-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep
cp -pav %{SOURCE1} %{SOURCE2} .

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
