# Generated by rust2rpm 21
%bcond_without check
%global debug_package %{nil}

%global crate wasmparser

Name:           rust-%{crate}
Version:        0.83.0
Release:        %autorelease
Summary:        Simple event-driven library for parsing WebAssembly binary files

# Upstream license specification: Apache-2.0 WITH LLVM-exception
License:        ASL 2.0
URL:            https://crates.io/crates/wasmparser
Source:         %{crates_source}
# Initial patched metadata
# * exclude a file that is only useful for upstream development
Patch0:         wasmparser-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Simple event-driven library for parsing WebAssembly binary files.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+deterministic-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+deterministic-devel %{_description}

This package contains library source intended for building other packages which
use the "deterministic" feature of the "%{crate}" crate.

%files       -n %{name}+deterministic-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
