name: Run urlwatch
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  spec_update:
    name: "Update spec files"
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Download latest tarball
        run: curl -sLO https://src.fedoraproject.org/lookaside/rpm-specs-latest.tar.xz
        
      - name: Extract tarball
        run: tar xf rpm-specs-latest.tar.xz
        
      - name: Store updated specs
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: specs
          FOLDER: rpm-specs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: false
